### ISSUE TITLE
[bug | 0.4.0] Error running the quarry with latest tech reborn and mod in 1.17

### ISSUE THREAD

**Issue by campbebj** [TED-inc/FabricQuarry#15]
Ive got the latest mod and latest tech reborn in 1.17 but after a few seconds the quary just crashes the server.

crashlog snipit below

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 9/18/21, 5:57 PM
Description: Ticking block entity

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1922.method_8320(net.minecraft.class_2338)" because "world" is null
	at net.minecraft.class_4970$class_4971.handler$cjm000$onGetHardness(class_4970.java:2617)
	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tryDrillDownTube(QuarryBlockEntity.java:279)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:182)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:43)
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77)
	at net.minecraft.class_2818$class_5563.redirect$bim000$checkProcessTEs(class_2818.java:1010)
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$zon000$ficUpdateSuppressionCrashTick(MinecraftServer.java:4273)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:891)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$bij000$modifiedRunLoop(MinecraftServer.java:8390)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraft.class_4970$class_4971.handler$cjm000$onGetHardness(class_4970.java:2617)
	at net.minecraft.class_4970$class_4971.method_26214(class_4970.java)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tryDrillDownTube(QuarryBlockEntity.java:279)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:182)
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:43)
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77)
	at net.minecraft.class_2818$class_5563.redirect$bim000$checkProcessTEs(class_2818.java:1010)

-- Block entity being ticked --
Details:
	Name: quarrymod:quarry // net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity
	Block: Block{quarrymod:quarry}[active=false,facing=south,state=off]
	Block location: World: (341,74,855), Section: (at 5,10,7 in 21,4,53; chunk contains blocks 336,-64,848 to 351,319,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
	Block: Block{quarrymod:quarry}[active=false,facing=south,state=off]
	Block location: World: (341,74,855), Section: (at 5,10,7 in 21,4,53; chunk contains blocks 336,-64,848 to 351,319,863), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,-64,512 to 511,319,1023)
Stacktrace:
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:886)
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:941)
	at net.minecraft.class_1937.method_18471(class_1937.java:474)
	at net.minecraft.class_3218.method_18765(class_3218.java:422)
	at net.minecraft.server.MinecraftServer.redirect$zon000$ficUpdateSuppressionCrashTick(MinecraftServer.java:4273)
```

**Comment by TED-inc** [comment]
Thanks for your report. I'm looking at it

**Comment by TED-inc** [comment]
Please, check new 0.4.3 version
