### ISSUE TITLE
[bug | 0.5.5] - Instant Crash when using the Quarry - game breaking

### ISSUE THREAD

**Issue by joshuaberube** [TED-inc/FabricQuarry#37]
**Describe the bug**
Based on the crash report it seems there's an issue with the sound the Quarry uses, so when it tries to access it, it crashes the game instantly.

**To Reproduce**
Place a quarry down and power it, your game will crash. If you try going back into the world, your game will freeze, and eventually crash.

**Expected behavior**
I expect the game to not crash and the quarry to work

**Mods versions:**
 - Quarry Reborn: 0.5.5
 - Tech Reborn: 5.1.0
 - Fabric API: 0.46.6
 
 
 **quick crash report**
 [13:34:48] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.class_148: Ticking block entity
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:883) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:823) ~[client-intermediary.jar:?]
	at net.minecraft.class_1132.method_3748(class_1132.java:99) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:684) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[client-intermediary.jar:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NoSuchFieldError: soundHanlder
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tickQuarryLogic(QuarryBlockEntity.java:219) ~[quarry-reborn-1.18-0.5.5.jar:?]
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:168) ~[quarry-reborn-1.18-0.5.5.jar:?]
	at net.quarrymod.blockentity.machine.tier3.QuarryBlockEntity.tick(QuarryBlockEntity.java:47) ~[quarry-reborn-1.18-0.5.5.jar:?]
	at reborncore.common.BaseBlockEntityProvider.lambda$getTicker$0(BaseBlockEntityProvider.java:77) ~[RebornCore-5.1.0.jar:?]
	at net.minecraft.class_2818$class_5563.method_31703(class_2818.java:659) ~[client-intermediary.jar:?]
	at net.minecraft.class_2818$class_5564.method_31703(class_2818.java:713) ~[client-intermediary.jar:?]
	at net.minecraft.class_1937.method_18471(class_1937.java:477) ~[client-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:365) ~[client-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:879) ~[client-intermediary.jar:?]
	... 5 more
[13:34:48] [Server thread/ERROR]: This crash report has been saved to: C:\Users\Josh\curseforge\minecraft\Instances\Vanilla+\crash-reports\crash-2022-03-06_13.34.48-server.txt
[13:34:48] [Server thread/INFO]: Stopping server
[13:34:48] [Server thread/INFO]: Saving players
[13:34:48] [Thread-5/INFO]: Minecraft instance shutting down, starting the Illuminations uninstaller

**Comment by TED-inc** [comment]
Thanks for report, I will fix it

**Comment by TED-inc** [comment]
Fixed in 0.5.6
